# fly.toml app configuration file generated for factorio-mc on 2024-11-05T20:36:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'factorio-mc'
primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'factoriotools/factorio:2.0.14'

[env]
  BIND = 'fly-global-services'
  DLC_SPACE_AGE = 'false'
  PRIMARY_REGION = 'lhr'

[[mounts]]
  source = 'factorio_data'
  destination = '/factorio'
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 34197
  min_machines_running = 1

  [[services.ports]]
    port = 34197

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
