# fly.toml app configuration file generated for factorio-mc on 2024-10-21T19:21:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'factoriotools/factorio:latest'

[env]
  PRIMARY_REGION = 'lhr'

[[mounts]]
  source = 'factorio_data'
  destination = '/factorio'
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = "34197"

  [[services.ports]]
    port = "34197"

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  internal_port = "27015"
  protocol = "tcp"

  [[services.ports]]
    port = "27015"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
